baseURL = "http://solucoesengenharia.github.io/"
languageCode = "en-us"
title = "Soluções Engenharia"
theme = "minimal"
googleAnalytics = ""

[params]
    author = "Calin Tataru"
    description = "Soluções de engenharia industrial, recuperação de equipamentos, proteção contra corrosão e erosão."
    githubUsername = "#"
    accent = "orange"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

#[[menu.main]]
 #   url = "/"
  #  name = "Ínicio"
   # weight = 1

#[[menu.main]]
 #   url = "/about/"
  #  name = "Sobre"
   # weight = 2

#[[menu.main]]
 #   url = "/Projects/"
  #  name = "Projetos"
   # weight = 3

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:eduardo.javier@hita.com.br"
    name = "envelope-o"
    weight = 1
